name: codeharbor

services:
  control-panel:
    build:
      context: .
      dockerfile: control-panel/Dockerfile
    environment:
      - AUTH_GITHUB_ID=${AUTH_GITHUB_ID:?error}
      - AUTH_GITHUB_SECRET=${AUTH_GITHUB_SECRET:?error}
      - DOCKER_GROUP_ID=${DOCKER_GROUP_ID:?error}
      - OPENVSCODE_SERVER_MOUNT_PATH=${OPENVSCODE_SERVER_MOUNT_PATH:?error}
      - BASE_DOMAIN=${BASE_DOMAIN:?error}
      - DOCKER_NETWORK_NAME=${DOCKER_NETWORK_NAME:-codeharbor}
      # If not behind proxy
      - ORIGIN=${ORIGIN:?error}}
      # If behind proxy (e.g. Cloudflare Tunnel)
      # - PROTOCOL_HEADER=x-forwarded-proto
      # - HOST_HEADER=x-forwarded-host
      - DATABASE_URL=/usr/src/app/db/local.db
    volumes:
      - type: bind
        source: ${DATABASE_DIR:?error}
        target: /usr/src/app/db
      - type: bind
        source: ${DOCKER_SOCKET_PATH:-/var/run/docker.sock}
        target: /var/run/docker.sock
    group_add:
      - '${DOCKER_GROUP_ID:?error}'
    init: true
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - '${GATEWAY_PORT:-5110}:5110'
    environment:
      - BASE_DOMAIN=${BASE_DOMAIN:?error}
      - CONTROL_PANEL_HOST=control-panel:3000
      - DATABASE_URL=/usr/src/app/db/local.db
      - GATEWAY_IN_CONTAINER=true
    volumes:
      - type: bind
        source: ${DATABASE_DIR:?error}
        target: /usr/src/app/db
      - type: bind
        source: ${DOCKER_SOCKET_PATH:-/var/run/docker.sock}
        target: /var/run/docker.sock
    depends_on:
      - control-panel
    group_add:
      - '${DOCKER_GROUP_ID:?error}'
    init: true
    networks:
      - codeharbor
      - default
  # If using Cloudflare Tunnel
  # cloudflared:
  #   image: cloudflare/cloudflared:latest
  #   command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TUNNEL_TOKEN:?error}
  #   restart: unless-stopped
networks:
  codeharbor:
    external: true
    name: ${DOCKER_NETWORK_NAME:-codeharbor}