name: codeharbor

services:
  control-panel:
    build:
      context: .
      dockerfile: control-panel/Dockerfile
    environment:
      - AUTH_GITHUB_ID=${AUTH_GITHUB_ID:?error}
      - AUTH_GITHUB_SECRET=${AUTH_GITHUB_SECRET:?error}
      - DOCKER_GROUP_ID=${DOCKER_GROUP_ID:?error} # stat -c '%g' /var/run/docker.sock
      - ORIGIN=http://${GATEWAY_ROOT_DOMAIN:?error}:${GATEWAY_PORT:-5110}
      - DATABASE_URL=/usr/src/app/db/local.db
    volumes:
      - type: bind
        source: ${DATABASE_DIR:?error}
        target: /usr/src/app/db
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    group_add:
      - '${DOCKER_GROUP_ID:?error}' # stat -c '%g' /var/run/docker.sock
    init: true
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - '${GATEWAY_PORT:-5110}:5110'
    environment:
      - GATEWAY_ROOT_DOMAIN=${GATEWAY_ROOT_DOMAIN:?error}
      - CONTROL_PANEL_HOST=control-panel:3000
      - DATABASE_URL=/usr/src/app/db/local.db
    volumes:
      - type: bind
        source: ${DATABASE_DIR:?error}
        target: /usr/src/app/db
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    depends_on:
      - control-panel
    group_add:
      - '${DOCKER_GROUP_ID:?error}' # stat -c '%g' /var/run/docker.sock
    init: true
